version: '3.8'
services:
    db:
        image: mysql:5.7
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=portal_conciliador_transportadora
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
        image: localstack/localstack
        network_mode: bridge
        restart: always
        ports:
            - "4566:4566"
            - "4571:4571"
            - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
        environment:
            - SERVICES=${SERVICES- }
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - PORT_WEB_UI=${PORT_WEB_UI- }
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=/tmp/localstack/data
        volumes:
            - "./tmp/localstack_data:/tmp/localstack/data"
            - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    db:
        driver: local
